const ACTIVITY_LABELS: Record<number, string> = {
  1: "Issue Created",
  2: "Issue Updated",
  3: "Issue Commented",
  4: "Issue Deleted",
  5: "Wiki Created",
  6: "Wiki Updated",
  7: "Wiki Deleted",
  8: "File Added",
  9: "File Updated",
  10: "File Deleted",
  11: "SVN Committed",
  12: "Git Pushed",
  13: "Git Repo Created",
  14: "Issue Multi-Updated",
  15: "Project User Added",
  16: "Project User Removed",
  17: "Notification Added",
  18: "Pull Request Added",
  19: "Pull Request Updated",
  20: "Pull Request Commented",
  21: "Pull Request Deleted",
  22: "Milestone Added",
  23: "Milestone Updated",
  24: "Milestone Deleted",
  25: "Project Team Added",
  26: "Project Team Deleted",
  34: "Status Deleted",
  35: "Issues Dates Updated",
  36: "Document Created",
  37: "Document Deleted",
  38: "Document Title Updated",
  39: "Document Updated",
  40: "Document Commented",
  41: "Document Comment Updated",
  42: "Document Comment Deleted",
  43: "Document Comment Replied",
  44: "Document Comment Reply Updated",
  45: "Document Comment Reply Deleted",
  46: "Document Attachment Added",
  47: "Issue Multi-Created",
  48: "Document Multi-Created",
  49: "Document Mentioned",
  50: "Related Issue Added",
  51: "Related Issue Removed",
};

export { ACTIVITY_LABELS };
