const ACTIVITY_LABELS: Record<number, string> = {
  1: "Issue Created",
  2: "Issue Updated",
  3: "Issue Commented",
  4: "Issue Deleted",
  5: "Wiki Created",
  6: "Wiki Updated",
  7: "Wiki Deleted",
  8: "File Added",
  9: "File Updated",
  10: "File Deleted",
  11: "SVN Committed",
  12: "Git Pushed",
  13: "Git Repo Created",
  14: "Issue Multi-Updated",
  15: "Project User Added",
  16: "Project User Removed",
  17: "Notification Added",
  18: "Pull Request Added",
  19: "Pull Request Updated",
  20: "Pull Request Commented",
  21: "Pull Request Deleted",
  22: "Milestone Added",
  23: "Milestone Updated",
  24: "Milestone Deleted",
  25: "Project Team Added",
  26: "Project Team Deleted",
  34: "Status Deleted",
  35: "Issues Dates Updated",
  47: "Issue Multi-Created",
};

export { ACTIVITY_LABELS };
