name: Bug report
description: Report a bug
labels: [bug]
body:
  - type: markdown
    attributes:
      value: |
        You can write in English or Japanese. / 英語または日本語で記述できます。
  - type: textarea
    id: description
    attributes:
      label: Description
      description: What happened? What did you expect?
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
  - type: input
    id: version
    attributes:
      label: bee version
      placeholder: e.g. 0.1.0
