name: Feature request
description: Suggest a feature
labels: [enhancement]
body:
  - type: markdown
    attributes:
      value: |
        You can write in English or Japanese. / 英語または日本語で記述できます。
  - type: textarea
    id: description
    attributes:
      label: Description
      description: What would you like to see?
    validations:
      required: true
