name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: read

jobs:
  ci:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      pull-requests: write

    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1

      - uses: jdx/mise-action@c37c93293d6b742fc901e1406b8f764f6fb19dac # v2.4.4

      - run: pnpm install --frozen-lockfile

      - name: Generate OpenAPI client
        run: pnpm --filter @repo/openapi build && pnpm --filter @repo/openapi-client build

      - name: Test
        run: pnpm exec vitest run --coverage.enabled

      - name: Report coverage
        if: always() && github.event_name == 'pull_request'
        uses: davelosert/vitest-coverage-report-action@v2

      - name: Lint & Type check
        run: pnpm exec oxlint --type-aware --type-check --ignore-pattern 'apps/docs' --max-warnings 0

      - name: Format check
        run: pnpm run format:check
